[pytest]
addopts = --alluredir=allure-results --clean-alluredir --log-cli-level=INFO
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

log_cli = true
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    ui: UI related test cases
    api: API related test cases
    db: Database related test cases
    hybrid: Tests that combine UI and API
    smoke: Critical path tests
    regression: Full regression suite
    functional: Marks tests as functional tests
    flaky: Marks test to rerun on failure
    pratish: anything
    arsha: hi
