[pytest]
addopts = --alluredir=allure-results --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: UI related test cases
    api: API related test cases
    db: Database related test cases
    hybrid: Tests that combine UI and API
    smoke: Critical path tests
    regression: Full regression suite