
browser:
  default: "chrome"
  headless: false
  implicit_wait: 10
  page_load_timeout: 30

environments:
  dev:
    base_url: "https://testautomationpractice.blogspot.com/"
    username: "admin"
    password: "password"
  staging:
    base_url: "https://testautomationpractice.blogspot.com/"
    username: "admin"
    password: "password"
  prod:
    base_url: "https://testautomationpractice.blogspot.com/"
    username: "admin"
    password: "password"
  orenge_pet:
    base_url: "https://www.orangepet.in/"
    username: "arijitsarkar999@gmail.com"
    password: "Arijit@1234"
    
    
    
    
  aqua:
    base_url: "https://www.orangepet.in"
    username: "rangamlavanyars@gmail.com"
    password: "Srinivas@jaya1"
      
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
